### ISSUE TITLE
Thanks for the project

### ISSUE THREAD

**Issue by paskal** [Freezystem/xidel#1]
Hi there! I am trying to build a simple script for monit which supposed to check sitemap.xml dates and notify me if these dates are too old. I've tried to use `xmlstarlet` but it for some reason didn't want to fetch remote URL. Next, I've tried to use `xidel` which worked perfectly for me and was easy to test thanks to your Docker image.

So after a long introduction, thanks a lot for publishing this repo: it's very useful for me and I'll copy the code to my monitoring image Dockerfile.

**Comment by Freezystem** [comment]
Hi @paskal, thanks a lot for this message. I'm glad it helped. 😇

I've originally created this docker image because I was testing several xpath queriers as docker executable command.

Despite I'm not the Xidel creator, I've spent some time tweaking this image to work as best as it can so it's a good thing that it's used by someone.

Feel free to report me any problem you encounter to see if we can find ways to fix it.

Have a nice day.
